const IMAGES = {
  LOAD: "IMAGES_LOAD",
  LOAD_SUCCESS: "IMAGES_LOAD_SUCCESS",
  LOAD_FAILED: "IMAGES_LOAD_FAILED"
};

const IMAGE_DETAILS = {
  LOAD: "IMAGE_DETAILS_LOAD",
  LOAD_SUCCESS: "IMAGES_DETAILS_LOAD_SUCCESS",
  LOAD_FAILED: "IMAGES_DETAILS_LOAD_FAILED"
};

export { IMAGES, IMAGE_DETAILS };
